apiVersion: v1
kind: PersistentVolume
metadata:
  name: cyberark-sdk-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/data/cyberark-sdk