apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyberark-sdk-pvc
spec:
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  nodeaffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - devsecops-demo-cluster-control-plane 