apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cyberark-sdk-pvc2
spec:
  storageClassName: local-path-resizeable
  allowVolumeExpansion: true
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi